const API_KEY = '07f737e9bca34a405ca1ff83b3a56544';

const TOKEN =
  'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwN2Y3MzdlOWJjYTM0YTQwNWNhMWZmODNiM2E1NjU0NCIsIm5iZiI6MTczNDE4NDEwMi43MDQsInN1YiI6IjY3NWQ4Y2E2NzNlOTU3YTAxYTg3ZTEwZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.wWKUxmLtUp0_jSpS3NqacVXN62hOr1ni1Bc08lK0FrE';

enum sections {
  POPULERTV = 'POPULERTV',
  POPULERMOVIES = 'POPULERMOVIES',
  TOPRATEDMOVIES = 'TOPRATEDMOVIES',
  TOPRATEDTV = 'TOPRATEDTV',
}

enum itemTypes {
  MOVIE = 'MOVIE',
  TV = 'TV',
}

export { API_KEY, TOKEN, sections, itemTypes };
